---
title: "P8131_HW7"
output: pdf_document
date: "2023-04-11"
author: "Zirui Zhang (zz3039)"
---

```{r chunk_setup, message=FALSE}
library(readr)
library(tidyverse)
library(dplyr)
library(nlme)
library(lme4)
```

### Question (a)

```{r chunk_qa, message=FALSE, warning=FALSE}
# load data
pl = read.csv("./HW7-politeness_data.csv") 
attach(pl)
# boxplot
boxplot(frequency~gender, xlab="gender", ylab="pitch")
boxplot(frequency~attitude, xlab="attitude", ylab="pitch")
```

### Question (b)

```{r}
# fit LMM with random intercept
lmm1 = lme(frequency ~ gender+attitude, random=~1 | subject, data=pl, method="REML" )
summary(lmm1)
```

The covariance matrix for a subject $Y_{i}$ is:

$$
cov(Y_i) = 
\begin{bmatrix}
\sigma^2 + \sigma_{b}^2  & \sigma_{b}^2 & ... & \sigma_{b}^2 \\
\sigma_{b}^2 & \sigma^2 + \sigma_{b}^2 & ... & \sigma_{b}^2 \\
... & \\
\sigma_{b}^2 & \sigma_{b}^2 & ... & \sigma^2 + \sigma_{b}^2 
\end{bmatrix}
$$
where $$ \sigma^2  = `r as.numeric(VarCorr(lmm1)[2])`, \sigma_{b}^2 = `r as.numeric(VarCorr(lmm1)[1])`$$



```{r}
# covariance matrix for estimates of fixed effects
vcov(lmm1)
# BLUPs for subject-specific intercepts
random.effects(lmm1)
# residuals
pl$frequency-fitted(lmm1)
```

### Question (c)

```{r}
lmm2.1 = lme(frequency ~ gender+attitude, random=~1|subject, data=pl, method="ML" )
lmm2.2 = lme(frequency ~ gender+attitude+gender*attitude, random=~1|subject, data=pl, method="ML" )
anova(lmm2.1, lmm2.2)
```

The P-value is greater than 0.05, thus we fail to reject the null and use the smaller model without the interaction term.

### Question (d)

```{r}
# fit LMM with random intercepts for subject and scenario
lmm3 = lmer(frequency ~ gender + attitude + (1|subject) + (1|scenario), data=pl)
summary(lmm3)
VarCorr(lmm3)
```

The covariance matrix for a subject $Y_{i}$ is:

$$
cov(Y_i) = 
\begin{bmatrix}
\sigma^2 + \sigma_{b_{1}}^2 + \sigma_{b_{2}}^2 & \sigma_{b_{1}}^2 + \sigma_{b_{2}}^2 & ... & \sigma_{b_{1}}^2 + \sigma_{b_{2}}^2 \\
\sigma_{b_{1}}^2 + \sigma_{b_{2}}^2 & \sigma^2 + \sigma_{b_{1}}^2 + \sigma_{b_{2}}^2 & ... & \sigma_{b_{1}}^2 + \sigma_{b_{2}}^2 \\
... & \\
\sigma_{b_{1}}^2 + \sigma_{b_{2}}^2 & \sigma_{b_{1}}^2 + \sigma_{b_{2}}^2 & ... & \sigma^2 + \sigma_{b_{1}}^2 + \sigma_{b_{2}}^2 
\end{bmatrix}
$$
where $$ \sigma^2  = `r round((summary(lmm3)$sigma)^2, 2)`, \sigma_{b_{1}}^2 = `r round(as.numeric(VarCorr(lmm3)[2]), 2)`, , \sigma_{b_{2}}^2 = `r round(as.numeric(VarCorr(lmm3)[1]), 2)`$$
